# Generated by Django 5.0 on 2023-12-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_notification', models.DateField()),
                ('last_date_for_application', models.DateField()),
                ('exam_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('keywords', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('application_link', models.URLField()),
                ('important_resources_1', models.URLField()),
                ('important_resources_2', models.URLField()),
                ('syllabus', models.TextField()),
            ],
        ),
    ]
