# Generated by Django 5.0 on 2023-12-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(choices=[('civil', 'Civil Exams'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('popular', 'Popular')], max_length=50),
        ),
    ]
