# Generated by Django 5.0 on 2023-12-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_exam_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='application_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(blank=True, choices=[('civil', 'Civil Exams'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('popular', 'Popular')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date_of_notification',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='important_resources_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='important_resources_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='last_date_for_application',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='syllabus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
