# Generated by Django 5.0 on 2023-12-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_exam_application_link_alter_exam_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(blank=True, choices=[('UPSC', 'Civil Exams'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('popular', 'Popular')], max_length=50, null=True),
        ),
    ]
