# Generated by Django 5.0 on 2023-12-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_exam_exam_description_alter_exam_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='eligibility_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.CharField(blank=True, choices=[('UPSC', 'UPSC'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('popular', 'Popular')], max_length=50, null=True),
        ),
    ]
