# Generated by Django 5.0 on 2023-12-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_exam_eligibility_criteria_alter_exam_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='important_resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
