# Generated by Django 5.0 on 2024-01-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exam_more_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
