# Generated by Django 5.0 on 2023-12-23 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_notification', models.DateField(blank=True, null=True)),
                ('last_date_for_application', models.DateField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('UPSC', 'UPSC'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('popular', 'Popular')], max_length=50, null=True)),
                ('application_link', models.URLField(blank=True, null=True)),
                ('important_resources_1', models.URLField(blank=True, null=True)),
                ('important_resources_2', models.URLField(blank=True, null=True)),
                ('syllabus', models.TextField(blank=True, null=True)),
                ('exam_description', models.TextField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('important_resources', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam')),
            ],
        ),
    ]
