# Generated by Django 5.0 on 2023-12-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_exam_important_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='category',
        ),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ManyToManyField(blank=True, choices=[('UPSC', 'UPSC'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('popular', 'Popular')], null=True, to='main.category'),
        ),
    ]
