# Generated by Django 5.0 on 2023-12-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_remove_exam_category_exam_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('UPSC', 'UPSC'), ('engineering', 'Engineering'), ('medical', 'Medical'), ('popular', 'Popular')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.ManyToManyField(blank=True, to='main.category'),
        ),
    ]
