# Generated by Django 5.0 on 2024-01-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_name_alter_exam_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
